### ISSUE TITLE
Problem when Navigate

### ISSUE THREAD

**Issue by fabioebner** [appreciated/vaadin-app-layout#101]
I have one view, to Create or Update a ticket, so When I navigate to that view with no parameter(http://localhost:8080/#!protocolo-td) in URL the view open with all buttons enabled, and when I save that view I navigate to same view but now with parameters (http://localhost:8080/#!protocolo-td/3050&t=1519220726128) the vaadin execute my method (public void enter(ViewChangeEvent event) {)  but don`t change my stats in view (sample If i disable a button, the button don't disable in screen) do you know why (If I don`t use r layout, works fine)

**Comment by appreciated** [comment]
Please add some sample code.

**Comment by fabioebner** [comment]
Ok.. let`s go :

MyUI.app
```

//@Push
//@PushStateNavigation
@Viewport("width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no")
@SpringUI
@Theme("mytheme")
@MenuCaption("UI")
@Title("RTDPJ - WEB")
public class MyUI extends UI {


	private final SpringViewProvider viewProvider;
	private final NavigationManager navigationManager;
	public static Navigator navigator;

	@Autowired
	public MyUI(SpringViewProvider viewProvider, NavigationManager navigationManager,UsuarioService usuarioService, FinanceiroService financeiroService) {
	    this.viewProvider = viewProvider;
	    this.navigationManager = navigationManager;
	    this.usuarioService = usuarioService;
	    this.financeiroService = financeiroService;
	}

  	DefaultNotificationHolder notifications = new DefaultNotificationHolder();
    DefaultBadgeHolder badge = new DefaultBadgeHolder();
    @Override
    protected void init(VaadinRequest vaadinRequest) {

        setContent(AppLayout.getCDIBuilder(Behaviour.LEFT_RESPONSIVE_HYBRID)
                .withViewProvider(() -> viewProvider)
                .withNavigationElementInfoProvider(new DefaultSpringNavigationElementInfoProvider())
                .withTitle("RTDPJ - Web")
                .addToAppBar(new AppBarNotificationButton(notifications, true))
                .withDesign(AppBarDesign.MATERIAL)
                .add(new MenuHeader("Version 0.9.20", new ThemeResource("logo.png")), AppLayoutConfiguration.Position.HEADER)
                .add(badge,BalcaoImpl.class)

                .add(CDISubmenuBuilder.get("NOVO", VaadinIcons.PLUS)
                        .add(ViewTestImpl.class)
                        .build())

                .build());

        badge.setCount(4);
        notifications.addNotification(new DefaultNotification("Teste", "1"));
        notifications.addNotification(new DefaultNotification("Title1", "Descricao", VaadinIcons.ACADEMY_CAP, DefaultNotification.Priority.HIGH, false));
        notifications.addNotification(new DefaultNotification("Title2", "Descricao2", VaadinIcons.ACADEMY_CAP, DefaultNotification.Priority.MEDIUM, false));
        notifications.addNotification(new DefaultNotification("Title3", "Descricao3", VaadinIcons.ACADEMY_CAP, DefaultNotification.Priority.LOW, true));

    }

}


```
My ViewTest.html
```
<!doctype html>
<html>
 <head>
  <meta charset="UTF-8">
  <meta name="design-properties" content="{&quot;RULERS_VISIBLE&quot;:true,&quot;GUIDELINES_VISIBLE&quot;:false,&quot;SNAP_TO_OBJECTS&quot;:true,&quot;SNAP_TO_GRID&quot;:true,&quot;SNAPPING_DISTANCE&quot;:10,&quot;GENERATE_GETTERS&quot;:false,&quot;JAVA_SOURCES_ROOT&quot;:&quot;src/main/java&quot;,&quot;THEME&quot;:&quot;material&quot;}">
  <meta name="vaadin-version" content="8.0.5">
 </head>
 <body>
  <vaadin-vertical-layout size-full>
   <vaadin-button plain-text _id="btnTeste">
     Save 
   </vaadin-button>
   <vaadin-button plain-text _id="btnEdit">
     Edit 
   </vaadin-button>
  </vaadin-vertical-layout>
 </body>
</html>

```
My ViewTest.java (Created by Vaadin Designer)
```

@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class ViewTest extends VerticalLayout {
    protected Button btnTeste;
    protected Button btnEdit;

    public ViewTest() {
        Design.read(this);
    }
}


```

and my ViewTestImpl

```

@ViewScope
@SpringView(name = "teste")
@MenuCaption("teste")
@MenuIcon(VaadinIcons.ACADEMY_CAP)
public class ViewTestImpl extends ViewTest implements View{
    @Autowired
    private NavigationManager navigationManager;

    public ViewTestImpl() {
        btnTeste.addClickListener(evt->btnTesteListener());
        btnEdit.addClickListener(evt->liberarEditar());
    }

    private void liberarEditar() {
        btnTeste.setEnabled(true);
        btnEdit.setEnabled(false);
    }

    private void btnTesteListener() {
        btnTeste.setEnabled(!btnTeste.isEnabled());
        navigationManager.navigateTo(ViewTestImpl.class, 1L);
    }

    @Override
    public void enter(ViewChangeListener.ViewChangeEvent event) {

        Long id = null;
        if(!Strings.isNullOrEmpty(event.getParameters())){
            String[] parametros = event.getParameters().split("&");
            id = Long.parseLong(parametros[0]);
        }

        if(id != null){
            System.out.println("enter with ID: "+id+", must enable the edit button and disable the save button");
            btnTeste.setEnabled(false);
            btnEdit.setEnabled(true);
        }else{
            System.out.println("enter with ID: null, must enable the save button and disable the edit button");
            btnTeste.setEnabled(true);
            btnEdit.setEnabled(false);
        }
    }
}
```

My NavigationManager.java


```
@Component
@UIScope
public class NavigationManager extends SpringNavigator {

    /**
     * Find the view id (URI fragment) used for a given view class.
     *
     * @param viewClass
     *            the view class to find the id for
     * @return the URI fragment for the view
     */
    public String getViewId(Class<? extends View> viewClass) {
        SpringView springView = viewClass.getAnnotation(SpringView.class);
        if (springView == null) {
            throw new IllegalArgumentException("The target class must be a @SpringView");
        }

        return Conventions.deriveMappingForView(viewClass, springView);
    }
    
	public void navigateTo(Class<? extends View> targetView, Object parameter) {
        String viewId = getViewId(targetView);
        navigateTo(viewId + "/" + parameter.toString() + "&t="+ Calendar.getInstance().getTimeInMillis());
    }

}
```

**Comment by appreciated** [comment]
I'm pretty sure that you should not do this `public static Navigator navigator;` 
Anyways if I use your code I get the following exception which isn't connected to the AppLayout but instead to the SpringViewProvider:
```
java.lang.IllegalArgumentException: Trying to navigate to an unknown state 'teste/1&t=1519392881413' and an error view provider not present
	at com.vaadin.navigator.Navigator.navigateTo(Navigator.java:661) ~[vaadin-server-8.3.1.jar:8.3.1]
	at com.example.demo.NavigationManager.navigateTo(NavigationManager.java:33) ~[classes/:na]
	at com.example.demo.ViewTestImpl.btnTesteListener(ViewTestImpl.java:32) ~[classes/:na]
	at com.example.demo.ViewTestImpl.lambda$new$61446b05$1(ViewTestImpl.java:21) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_161]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_161]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_161]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_161]
```

**Comment by fabioebner** [comment]
So in your addon. how can I navigate to another view when I click in a button inside my view?

**Comment by appreciated** [comment]
`Navigator::navigateTo(<viewname>)

**Comment by fabioebner** [comment]
I change my code to use a vaadin navigator more simple and the result are the same:

`package br.com.exmart.indicadorRTDPJ.ui.navigator;

import com.vaadin.navigator.Navigator;
import com.vaadin.navigator.View;
import com.vaadin.spring.annotation.SpringView;
import com.vaadin.spring.annotation.UIScope;
import com.vaadin.spring.internal.Conventions;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import java.util.Calendar;

@Component
@UIScope
public class NavigationManager {//extends SpringNavigator {
        @Autowired
        private Navigator navigator;

    public String getViewId(Class<? extends View> viewClass) {
        SpringView springView = viewClass.getAnnotation(SpringView.class);
        if (springView == null) {
            throw new IllegalArgumentException("The target class must be a @SpringView");
        }

        return Conventions.deriveMappingForView(viewClass, springView);
    }


    public void navigateTo(Class<? extends View> targetView, Object parameter) {
        String viewId = getViewId(targetView);
        this.navigator.navigateTo(viewId + "/" + parameter.toString() + "&t="+ Calendar.getInstance().getTimeInMillis());
    }


}`

**Comment by appreciated** [comment]
Please invite me to a working github repo with your code then I will help you
