### ISSUE TITLE
LeftMenu without LeftNavigationComponent

### ISSUE THREAD

**Issue by vrepetenko** [appreciated/vaadin-app-layout#203]
How to configure left menu which has only ClickableMenuItems?

If run application with left menu without Navigation Component there is error:

here was an exception while trying to navigate to ''

java.lang.NullPointerException: null
	at com.github.appreciated.app.layout.component.appmenu.left.LeftSubmenuComponent.getClosestNavigationElement(LeftSubmenuComponent.java:55) ~[app-layout-addon-2.0.2.jar:2.0.2]
	at com.github.appreciated.app.layout.builder.interfaces.NavigationElementContainer.lambda$getClosestNavigationElement$4(NavigationElementContainer.java:38) ~[app-layout-addon-2.0.2.jar:2.0.2]

**Comment by appreciated** [comment]
This is indeed a Bug please close this issue and fill out the correct issue template.
