### ISSUE TITLE
Release 2.1.0 - NoClassDefFoundError 

### ISSUE THREAD

**Issue by nrapel** [appreciated/vaadin-app-layout#258]
On Vaadin 13.0.3 I Upgraded from 2.1.0.beta1 to 2.1.0 I get the following error: 

```
java.lang.NoClassDefFoundError: com/vaadin/flow/router/RouteData$AliasData
	at com.github.appreciated.app.layout.router.navigation.RouteSimilarity.<init>(RouteSimilarity.java:23)
	at com.github.appreciated.app.layout.router.navigation.UpNavigationHelper.lambda$shouldHighlight$3(UpNavigationHelper.java:54)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1691)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:479)
	at java.util.stream.ReferencePipeline.max(ReferencePipeline.java:515)
	at com.github.appreciated.app.layout.router.navigation.UpNavigationHelper.shouldHighlight(UpNavigationHelper.java:55)
	at com.github.appreciated.app.layout.component.menu.left.items.LeftNavigationItem.lambda$new$96296b1d$1(LeftNavigationItem.java:50)
	at com.vaadin.flow.router.RouterLink.afterNavigation(RouterLink.java:335)
	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.lambda$fireAfterNavigationListeners$2(AbstractNavigationStateRenderer.java:305)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.fireAfterNavigationListeners(AbstractNavigationStateRenderer.java:305)
	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.handle(AbstractNavigationStateRenderer.java:235)
	at com.vaadin.flow.router.internal.ErrorStateRenderer.handle(ErrorStateRenderer.java:50)
	at com.vaadin.flow.router.Router.handleExceptionNavigation(Router.java:257)
	at com.vaadin.flow.router.Router.navigate(Router.java:192)
	at com.vaadin.flow.router.Router.initializeUI(Router.java:92)
	at com.vaadin.flow.server.BootstrapHandler.createAndInitUI(BootstrapHandler.java:1117)
	at com.vaadin.flow.server.BootstrapHandler.synchronizedHandleRequest(BootstrapHandler.java:396)
	at com.vaadin.flow.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
	at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1507)
	at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:242)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:71)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:651)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:409)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:754)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1376)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by appreciated** [comment]
I just "stopped" the 2.1.0 release. To prevent more users from getting a bad production experience. I need some time to evaluate this.

**Comment by appreciated** [comment]
So FYI 2.1.0 is not compatible with Vaadin 13 which I now added some notices at the Vaadin directory:
this is due to api differences in the Router API between Vaadin 12 and Vaadin 13. This wasn't a problem before since the app-layout did not support RouteAliases whichs support was added with #257, #255 ,#254 

 I will soon release asap a separate version for Vaadin 13 so you can continue using it. For now switch back to the beta.

**Comment by nrapel** [comment]
Fair enough!! Thanks for the quick response! :)

**Comment by appreciated** [comment]
[Checkout the beta for Vaadin 13](https://vaadin.com/directory/component/app-layout-add-on/3.0.0.beta1)

**Comment by nrapel** [comment]
Replacing 2.1.0.beta1 to 3.0.0.beta1 I receive the following error: 
On Tomcat 
`[http-nio-7080-exec-4] ERROR com.vaadin.flow.server.DefaultErrorHandler - 
org.apache.catalina.connector.ClientAbortException: java.io.IOException: An established connection was aborted by the software in your host machine
	at org.apache.catalina.connector.OutputBuffer.realWriteBytes(OutputBuffer.java:333)
	at org.apache.catalina.connector.OutputBuffer.appendByteArray(OutputBuffer.java:718)
	at org.apache.catalina.connector.OutputBuffer.append(OutputBuffer.java:647)
	at org.apache.catalina.connector.OutputBuffer.writeBytes(OutputBuffer.java:368)
	at org.apache.catalina.connector.OutputBuffer.write(OutputBuffer.java:346)
	at org.apache.catalina.connector.CoyoteOutputStream.write(CoyoteOutputStream.java:96)
	at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
	at sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:282)
	at sun.nio.cs.StreamEncoder.write(StreamEncoder.java:125)
	at java.io.OutputStreamWriter.write(OutputStreamWriter.java:207)
	at java.io.BufferedWriter.flushBuffer(BufferedWriter.java:129)
	at java.io.BufferedWriter.write(BufferedWriter.java:230)
	at java.io.Writer.write(Writer.java:157)
	at java.io.Writer.append(Writer.java:227)
	at com.vaadin.flow.server.BootstrapHandler.writeBootstrapPage(BootstrapHandler.java:570)
	at com.vaadin.flow.server.BootstrapHandler.synchronizedHandleRequest(BootstrapHandler.java:403)
	at com.vaadin.flow.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
	at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1507)
	at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:242)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:71)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:651)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:409)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:754)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1376)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: org.apache.catalina.connector.ClientAbortException: java.io.IOException: An established connection was aborted by the software in your host machine
		at org.apache.catalina.connector.OutputBuffer.realWriteBytes(OutputBuffer.java:333)
		at org.apache.catalina.connector.OutputBuffer.appendByteArray(OutputBuffer.java:718)
		at org.apache.catalina.connector.OutputBuffer.append(OutputBuffer.java:647)
		at org.apache.catalina.connector.OutputBuffer.writeBytes(OutputBuffer.java:368)
		at org.apache.catalina.connector.OutputBuffer.write(OutputBuffer.java:346)
		at org.apache.catalina.connector.CoyoteOutputStream.write(CoyoteOutputStream.java:96)
		at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
		at sun.nio.cs.StreamEncoder.implClose(StreamEncoder.java:316)
		at sun.nio.cs.StreamEncoder.close(StreamEncoder.java:149)
		at java.io.OutputStreamWriter.close(OutputStreamWriter.java:233)
		at java.io.BufferedWriter.close(BufferedWriter.java:266)
		at com.vaadin.flow.server.BootstrapHandler.writeBootstrapPage(BootstrapHandler.java:571)
		... 29 more
	Caused by: java.io.IOException: An established connection was aborted by the software in your host machine
		at sun.nio.ch.SocketDispatcher.write0(Native Method)
		at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:51)
		at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
		at sun.nio.ch.IOUtil.write(IOUtil.java:65)
		at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
		at org.apache.tomcat.util.net.NioChannel.write(NioChannel.java:134)
		at org.apache.tomcat.util.net.NioBlockingSelector.write(NioBlockingSelector.java:101)
		at org.apache.tomcat.util.net.NioSelectorPool.write(NioSelectorPool.java:157)
		at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.doWrite(NioEndpoint.java:1184)
		at org.apache.tomcat.util.net.SocketWrapperBase.doWrite(SocketWrapperBase.java:691)
		at org.apache.tomcat.util.net.SocketWrapperBase.writeBlocking(SocketWrapperBase.java:471)
		at org.apache.tomcat.util.net.SocketWrapperBase.write(SocketWrapperBase.java:409)
		at org.apache.coyote.http11.Http11OutputBuffer$SocketOutputBuffer.doWrite(Http11OutputBuffer.java:530)
		at org.apache.coyote.http11.filters.ChunkedOutputFilter.doWrite(ChunkedOutputFilter.java:110)
		at org.apache.coyote.http11.Http11OutputBuffer.doWrite(Http11OutputBuffer.java:189)
		at org.apache.coyote.Response.doWrite(Response.java:599)
		at org.apache.catalina.connector.OutputBuffer.realWriteBytes(OutputBuffer.java:328)
		... 40 more
Caused by: java.io.IOException: An established connection was aborted by the software in your host machine
	at sun.nio.ch.SocketDispatcher.write0(Native Method)
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:51)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
	at sun.nio.ch.IOUtil.write(IOUtil.java:65)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
	at org.apache.tomcat.util.net.NioChannel.write(NioChannel.java:134)
	at org.apache.tomcat.util.net.NioBlockingSelector.write(NioBlockingSelector.java:101)
	at org.apache.tomcat.util.net.NioSelectorPool.write(NioSelectorPool.java:157)
	at org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper.doWrite(NioEndpoint.java:1184)
	at org.apache.tomcat.util.net.SocketWrapperBase.doWrite(SocketWrapperBase.java:691)
	at org.apache.tomcat.util.net.SocketWrapperBase.writeBlocking(SocketWrapperBase.java:471)
	at org.apache.tomcat.util.net.SocketWrapperBase.write(SocketWrapperBase.java:409)
	at org.apache.coyote.http11.Http11OutputBuffer$SocketOutputBuffer.doWrite(Http11OutputBuffer.java:530)
	at org.apache.coyote.http11.filters.ChunkedOutputFilter.doWrite(ChunkedOutputFilter.java:112)
	at org.apache.coyote.http11.Http11OutputBuffer.doWrite(Http11OutputBuffer.java:189)
	at org.apache.coyote.Response.doWrite(Response.java:599)
	at org.apache.catalina.connector.OutputBuffer.realWriteBytes(OutputBuffer.java:328)
	... 43 more
Απρ 16, 2019 11:19:58 ΠΜ org.apache.catalina.core.StandardWrapperValve invoke`

and on Chrome :
Error loading http://localhost:8080/demoprojectui/bower_components/polymer/lib/elements/custom-style.html
client-3B1D64116B46DEBA7ADE32AB75416693.cache.js:376 GET http://localhost:8080/demoprojectui/bower_components/polymer/lib/elements/custom-style.html net::ERR_ABORTED 404
client-3B1D64116B46DEBA7ADE32AB75416693.cache.js:196 Error loading http://localhost:8080/demoprojectui/bower_components/polymer/lib/elements/custom-style.html
zB @ client-3B1D64116B46DEBA7ADE32AB75416693.cache.js:196
cn @ client-3B1D64116B46DEBA7ADE32AB75416693.cache.js:957
bn @ client-3B1D64116B46DEBA7ADE32AB75416693.cache.js:727
em @ client-3B1D64116B46DEBA7ADE32AB75416693.cache.js:854
Dm @ client-3B1D64116B46DEBA7ADE32AB75416693.cache.js:983
(anonymous) @ client-3B1D64116B46DEBA7ADE32AB75416693.cache.js:934
sb @ client-3B1D64116B46DEBA7ADE32AB75416693.cache.js:425
vb @ client-3B1D64116B46DEBA7ADE32AB75416693.cache.js:850
(anonymous) @ client-3B1D64116B46DEBA7ADE32AB75416693.cache.js:589
error (async)
rm @ client-3B1D64116B46DEBA7ADE32AB75416693.cache.js:934
km @ client-3B1D64116B46DEBA7ADE32AB75416693.cache.js:891
Xj @ client-3B1D64116B46DEBA7ADE32AB75416693.cache.js:983
wj @ client-3B1D64116B46DEBA7ADE32AB75416693.cache.js:243
qj @ client-3B1D64116B46DEBA7ADE32AB75416693.cache.js:942
sj @ client-3B1D64116B46DEBA7ADE32AB75416693.cache.js:560
Tj @ client-3B1D64116B46DEBA7ADE32AB75416693.cache.js:983
d @ client-3B1D64116B46DEBA7ADE32AB75416693.cache.js:637
vj @ client-3B1D64116B46DEBA7ADE32AB75416693.cache.js:687
Iq @ client-3B1D64116B46DEBA7ADE32AB75416693.cache.js:926
Jq @ client-3B1D64116B46DEBA7ADE32AB75416693.cache.js:979
Kq @ client-3B1D64116B46DEBA7ADE32AB75416693.cache.js:963
Jo @ client-3B1D64116B46DEBA7ADE32AB75416693.cache.js:983
(anonymous) @ client-3B1D64116B46DEBA7ADE32AB75416693.cache.js:952
sb @ client-3B1D64116B46DEBA7ADE32AB75416693.cache.js:425
vb @ client-3B1D64116B46DEBA7ADE32AB75416693.cache.js:850
(anonymous) @ client-3B1D64116B46DEBA7ADE32AB75416693.cache.js:589
_f @ vaadinPush.js?v=1.4.3:2765
_invokeFunction @ vaadinPush.js?v=1.4.3:2754
_invokeCallback @ vaadinPush.js?v=1.4.3:2884
_websocket.onmessage @ vaadinPush.js?v=1.4.3:1457

**Comment by appreciated** [comment]
> and on Chrome :

Thanks for reporting, this already has a separate issue #259 and is not connected with the first issue.

**Comment by appreciated** [comment]
> An established connection was aborted by the software in your host machine

This usually happens if you redeploy you application and have an open browser with the old deployment open. Can you confirm this?

**Comment by nrapel** [comment]
No I've done all of those but still the problem persisted... I was probably because it couldn't find the #259  html and it would shutdown the socket.. 
Anyhow, long story short!! With 3.0.0.beta2 I don't see the error on either sides (client or server!) 
Thanks!!
