### ISSUE TITLE
Dynamic route registration leads to null pointer exception

### ISSUE THREAD

**Issue by stefanuebe** [appreciated/vaadin-app-layout#269]
# Use case 

A multi module maven project provides components intended to be used as a route / view. These views do not have a `@Route` annotation since they are not aware of any final application layouting.

The web application assembles the views by using the dynamic route configuration (added in Vaadin 13).

```
public class InitListener implements VaadinServiceInitListener {

    @Override
    public void serviceInit(ServiceInitEvent event) {

        RouteConfiguration applicationScope = RouteConfiguration.forApplicationScope();

        // simplified
        applicationScope.setRoute("dynamic-view1", DynamicView1.class, MainView.class);
        applicationScope.setRoute("dynamic-view2", DynamicView2.class, MainView.class);
        ...
    }
}
```

Also static routes are used (using the `@Route` annotation). These do not lead to the problem. 

# Problem
The result is a Null Pointer Exception when calculating the matching views (I guess to mark the matching element in the menu). The reason here is a empty Optional returned from `getRoute()` that automatically leads to a null value, which then is accessed inside the for-loop. 

# Expected behavior
1. In case of a null value, the for loop should be ignored (or handle it like an empty string)
2. Dynamic registered routes should be recognized like static routes.

Thanks :) 

# Exception
```
java.lang.NullPointerException: null
	at com.github.appreciated.app.layout.builder.interfaces.NavigationElementContainer.computeClosenessScore(NavigationElementContainer.java:77) ~[app-layout-addon-2.0.8.jar:2.0.8]
	at com.github.appreciated.app.layout.builder.interfaces.NavigationElementContainer.compareRoute(NavigationElementContainer.java:68) ~[app-layout-addon-2.0.8.jar:2.0.8]
	at com.github.appreciated.app.layout.builder.interfaces.NavigationElementContainer.lambda$getClosestNavigationElementForElements$8(NavigationElementContainer.java:58) ~[app-layout-addon-2.0.8.jar:2.0.8]
	at java.util.stream.ReduceOps$2ReducingSink.accept(ReduceOps.java:123) ~[na:1.8.0_181]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[na:1.8.0_181]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_181]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[na:1.8.0_181]
	at java.util.stream.SpinedBuffer$1Splitr.forEachRemaining(SpinedBuffer.java:364) ~[na:1.8.0_181]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[na:1.8.0_181]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_181]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[na:1.8.0_181]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_181]
	at java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:479) ~[na:1.8.0_181]
	at com.github.appreciated.app.layout.builder.interfaces.NavigationElementContainer.getClosestNavigationElementForElements(NavigationElementContainer.java:58) ~[app-layout-addon-2.0.8.jar:2.0.8]
	at com.github.appreciated.app.layout.builder.interfaces.NavigationElementContainer.getClosestNavigationElement(NavigationElementContainer.java:48) ~[app-layout-addon-2.0.8.jar:2.0.8]
	at com.github.appreciated.app.layout.builder.interfaces.NavigationElementContainer.lambda$getClosestNavigationElementForElements$7(NavigationElementContainer.java:56) ~[app-layout-addon-2.0.8.jar:2.0.8]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_181]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[na:1.8.0_181]
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:419) ~[na:1.8.0_181]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[na:1.8.0_181]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_181]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[na:1.8.0_181]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_181]
...
```

**Comment by stefanuebe** [comment]
My bad, we had an outdated version, I'll try with the newest one.

**Comment by appreciated** [comment]
No problem, just to let you know, there is already an open issue (#205) for the feature you describe. Currently this isn't supported 😞.
