### ISSUE TITLE
Vaadin 14 support with npm packaging

### ISSUE THREAD

**Issue by ajgassner** [appreciated/vaadin-app-layout#276]
Migrate to npm packaging to be compatible with Vaadin > 14. Since Vaadin 14 Bower packaging is deprecated.

**Comment by markusherr** [comment]
Is this planned any time soon?

**Comment by appreciated** [comment]
@markusherr I planned to begin with it today. But first I will port the [ApexCharts addon](https://github.com/appreciated/apexcharts-flow) to get some experience with npm. 
The app-layout is planned after that.

**Comment by markusherr** [comment]
That sounds great. I really appreciate it.

**Comment by markusherr** [comment]
I tried to use the migration too myself today and had these issues:
On windows 10 bower did not find GIT although it was installed and in the PATH. I  worked around that by starting the migration using the GIT Shell

I got this error from the migration tool: 
"FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory"
Worked around it by setting the NODE_OPIONS environment variable before doing the migration in GIT Shell like so:
``export NODE_OPTIONS=--max_old_space_size=4096"``
See https://github.com/vaadin/flow/issues/6250
I posted that workaround in the mentioned bug.

After that I got another error:

``Unhandled Rejection at: Promise  Promise {
  <rejected> TypeError: url.replace is not a function
      at Object.replaceHtmlExtensionIfFound (C:\work\GitRepositories\vaadin-app-layout\app-layout-addon\target\migration\node_modules\polymer-modulizer\src\urls\util.ts:32:14)
      at Object.generatePackageJson (C:\work\GitRepositories\vaadin-app-layout\app-layout-addon\target\migration\node_modules\polymer-modulizer\src\package-manifest.ts:205:24)
      at Object.<anonymous> (C:\work\GitRepositories\vaadin-app-layout\app-layout-addon\target\migration\node_modules\polymer-modulizer\src\convert-package.ts:133:23)
      at Generator.next (<anonymous>)
      at fulfilled (C:\work\GitRepositories\vaadin-app-layout\app-layout-addon\target\migration\node_modules\polymer-modulizer\lib\convert-package.js:17:58)
}  reason:  TypeError: url.replace is not a function
    at Object.replaceHtmlExtensionIfFound (C:\work\GitRepositories\vaadin-app-layout\app-layout-addon\target\migration\node_modules\polymer-modulizer\src\urls\util.ts:32:14)
    at Object.generatePackageJson (C:\work\GitRepositories\vaadin-app-layout\app-layout-addon\target\migration\node_modules\polymer-modulizer\src\package-manifest.ts:205:24)
    at Object.<anonymous> (C:\work\GitRepositories\vaadin-app-layout\app-layout-addon\target\migration\node_modules\polymer-modulizer\src\convert-package.ts:133:23)
    at Generator.next (<anonymous>)
    at fulfilled (C:\work\GitRepositories\vaadin-app-layout\app-layout-addon\target\migration\node_modules\polymer-modulizer\lib\convert-package.js:17:58)
``
See https://github.com/vaadin/flow/issues/6208

So migration is far from beeing smooth. In fact it didn't work at all for me.
Hope this helps a little.

**Comment by appreciated** [comment]
@markusherr this is not really an issue, the manual migration did not take that long an is mostly done.

**Comment by appreciated** [comment]
Closed by af0e31c16f5b319fcce3bf158c9a6c736ae4fdea
