### ISSUE TITLE
AppBarNotificationButton unstable

### ISSUE THREAD

**Issue by realulim** [appreciated/vaadin-app-layout#279]
When sending a Push Notification there appears to be an edge case that puts the AppBarNotificationButton in an inconsistent state. The only way I found to produce this inconsistent state is by automating the browser via Selenium. When testing manually, I appear to be too slow to trigger the bug. However, once the inconsistent state is created, I can then manually reproduce the bug.

What happens is this stacktrace when calling addNotification on a DefaultNotificationHolder:

```
java.lang.IllegalStateException: Cannot access state in VaadinSession or UI without locking the session.
	at com.vaadin.flow.server.VaadinSession.checkHasLock(VaadinSession.java:523) ~[flow-server-1.4.4.jar:1.4.4]
	at com.vaadin.flow.server.VaadinSession.checkHasLock(VaadinSession.java:537) ~[flow-server-1.4.4.jar:1.4.4]
	at com.vaadin.flow.internal.StateTree.checkHasLock(StateTree.java:390) ~[flow-server-1.4.4.jar:1.4.4]
	at com.vaadin.flow.internal.StateTree.markAsDirty(StateTree.java:258) ~[flow-server-1.4.4.jar:1.4.4]
	at com.vaadin.flow.internal.StateNode.markAsDirty(StateNode.java:510) ~[flow-server-1.4.4.jar:1.4.4]
	at com.vaadin.flow.internal.nodefeature.NodeList.addChange(NodeList.java:277) ~[flow-server-1.4.4.jar:1.4.4]
	at com.vaadin.flow.internal.nodefeature.NodeList.clear(NodeList.java:401) ~[flow-server-1.4.4.jar:1.4.4]
	at com.vaadin.flow.internal.nodefeature.StateNodeNodeList.clear(StateNodeNodeList.java:77) ~[flow-server-1.4.4.jar:1.4.4]
	at com.vaadin.flow.internal.nodefeature.ElementChildrenList.clear(ElementChildrenList.java:57) ~[flow-server-1.4.4.jar:1.4.4]
	at com.vaadin.flow.dom.impl.AbstractNodeStateProvider.removeAllChildren(AbstractNodeStateProvider.java:115) ~[flow-server-1.4.4.jar:1.4.4]
	at com.vaadin.flow.dom.Node.removeAllChildren(Node.java:363) ~[flow-server-1.4.4.jar:1.4.4]
	at com.vaadin.flow.component.HasComponents.removeAll(HasComponents.java:102) ~[flow-server-1.4.4.jar:1.4.4]
	at com.github.appreciated.app.layout.notification.component.NotificationsView.initView(NotificationsView.java:42) ~[app-layout-addon-3.0.0.beta5.jar:3.0.0.beta5]
	at com.github.appreciated.app.layout.notification.component.AppBarNotificationButton.refreshNotifications(AppBarNotificationButton.java:63) ~[app-layout-addon-3.0.0.beta5.jar:3.0.0.beta5]
	at com.github.appreciated.app.layout.notification.component.AppBarNotificationButton$1.onNotificationChanges(AppBarNotificationButton.java:37) ~[app-layout-addon-3.0.0.beta5.jar:3.0.0.beta5]
	at com.github.appreciated.app.layout.notification.NotificationHolder.lambda$notifyListeners$0(NotificationHolder.java:99) ~[app-layout-addon-3.0.0.beta5.jar:3.0.0.beta5]
	at java.util.ArrayList.forEach(ArrayList.java:1257) ~[na:1.8.0_181]
	at com.github.appreciated.app.layout.notification.NotificationHolder.notifyListeners(NotificationHolder.java:99) ~[app-layout-addon-3.0.0.beta5.jar:3.0.0.beta5]
	at com.github.appreciated.app.layout.notification.NotificationHolder.addNotification(NotificationHolder.java:93) ~[app-layout-addon-3.0.0.beta5.jar:3.0.0.beta5]
	at com.github.appreciated.app.layout.notification.DefaultNotificationHolder.addNotification(DefaultNotificationHolder.java:45) ~[app-layout-addon-3.0.0.beta5.jar:3.0.0.beta5]

```
It looks like the problem happens, when the NotificationView tries to rebuild itself and remove all its children. My application hasn't added any children to the NotificationView, I am just using the Push Notification feature as intended.

I realise that without a reproducible test case this is hard to fix. But perhaps someone has an idea what could theoretically put the application into this inconsistent state, from which I can only recover by restarting the app (reloading everything isn't enough).

**Comment by realulim** [comment]
I can reproduce the bug now simply by deploying to a slower remote server. It happens anytime I try to initialise the AppBarNotificationButton (basically when entering the Homepage):

```
Caused by: java.lang.IllegalStateException: Cannot access state in VaadinSession or UI without locking the session.
        at com.vaadin.flow.server.VaadinSession.checkHasLock(VaadinSession.java:523) ~[flow-server-1.4.4.jar!/:1.4.4]
        at com.vaadin.flow.server.VaadinSession.checkHasLock(VaadinSession.java:537) ~[flow-server-1.4.4.jar!/:1.4.4]
        at com.vaadin.flow.internal.StateTree.checkHasLock(StateTree.java:390) ~[flow-server-1.4.4.jar!/:1.4.4]
        at com.vaadin.flow.internal.StateTree.markAsDirty(StateTree.java:258) ~[flow-server-1.4.4.jar!/:1.4.4]
        at com.vaadin.flow.internal.StateNode.markAsDirty(StateNode.java:510) ~[flow-server-1.4.4.jar!/:1.4.4]
        at com.vaadin.flow.internal.nodefeature.NodeMap.setChanged(NodeMap.java:383) ~[flow-server-1.4.4.jar!/:1.4.4]
        at com.vaadin.flow.internal.nodefeature.NodeMap.put(NodeMap.java:195) ~[flow-server-1.4.4.jar!/:1.4.4]
        at com.vaadin.flow.internal.nodefeature.NodeMap.put(NodeMap.java:172) ~[flow-server-1.4.4.jar!/:1.4.4]
        at com.vaadin.flow.internal.nodefeature.ElementAttributeMap.set(ElementAttributeMap.java:68) ~[flow-server-1.4.4.jar!/:1.4.4]
        at com.vaadin.flow.dom.impl.BasicElementStateProvider.setAttribute(BasicElementStateProvider.java:183) ~[flow-server-1.4.4.jar!/:1.4.4]
        at com.vaadin.flow.dom.Element.setAttribute(Element.java:292) ~[flow-server-1.4.4.jar!/:1.4.4]
        at com.github.appreciated.app.layout.webcomponents.paperbadge.PaperBadge.setText(PaperBadge.java:33) ~[app-layout-addon-3.0.0.beta5.jar!/:3.0.0.beta5]
        at com.github.appreciated.app.layout.notification.NotificationHolder.updateBadgeCaption(NotificationHolder.java:121) ~[app-layout-addon-3.0.0.beta5.jar!/:3.0.0.beta5]
        at java.util.ArrayList.forEach(ArrayList.java:1257) ~[na:1.8.0_201]
        at com.github.appreciated.app.layout.notification.NotificationHolder.updateBadgeCaptions(NotificationHolder.java:107) ~[app-layout-addon-3.0.0.beta5.jar!/:3.0.0.beta5]
        at com.github.appreciated.app.layout.notification.NotificationHolder.bind(NotificationHolder.java:180) ~[app-layout-addon-3.0.0.beta5.jar!/:3.0.0.beta5]
        at com.github.appreciated.app.layout.notification.component.AppBarNotificationButton.<init>(AppBarNotificationButton.java:59) ~[app-layout-addon-3.0.0.beta5.jar!/:3.0.0.beta5]
```

**Comment by appreciated** [comment]
This usually only happens when you try calling it without `UI.getCurrent().access(() -> {...});`. This seems to be more of a usability issue.

**Comment by realulim** [comment]
It appears that you are absolutely right. My test suite now completes successfully, so I am not able to reproduce this behavior after changing my code as you recommended.

**Comment by appreciated** [comment]
With the next update an exception will be thrown:
```
Exception in Exception inthread "Thread-24"  thread "Thread-23" java.lang.IllegalStateException: It seems like NotificationHolder::add wasn't called from the UI Thread. This should be done by using "UI.getCurrent().access(() -> {})"
	...
```
