### ISSUE TITLE
UpNavigation with Hasparamater in v4 

### ISSUE THREAD

**Issue by weiliang2** [appreciated/vaadin-app-layout#317]
**Describe the bug**
Caused by: java.lang.IllegalArgumentException: Navigation target 'QuoteQtyView' requires a parameter and can not be resolved. Use 'public <T, C extends Component & HasUrlParameter<T>> String getUrl(Class<? extends C> navigationTarget, T parameter)' instead
	at com.vaadin.flow.router.RouteConfiguration.getUrl(RouteConfiguration.java:407) ~[flow-server-2.1.5.jar:2.1.5]
	at com.github.appreciated.app.layout.navigation.UpNavigationHelper.performUpNavigation(UpNavigationHelper.java:62) ~[app-layout-addon-4.0.0.rc5.jar:4.0.0.rc5]
	at com.github.appreciated.app.layout.component.applayout.AppLayout.onUpNavigation(AppLayout.java:41) ~[app-layout-addon-4.0.0.rc5.jar:4.0.0.rc5]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_241]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_241]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_241]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_241]
	at com.vaadin.flow.server.communication.rpc.PublishedServerEventHandlerRpcHandler.invokeMethod(PublishedServerEventHandlerRpcHandler.java:167) ~[flow-server-2.1.5.jar:2.1.5]
	... 99 common frames omitted

it used to work in the older version.

**Comment by appreciated** [comment]
So what needs to be done to reproduce the issue?

**Comment by weiliang2** [comment]
hello, 

view 1:

`@Route(value = "", layout = MainAppLayout.class)
public class View1 extends VerticalLayout {

    public View1() {
        Button navigate = new Button("Navigate to");
        navigate.addClickListener(e -> {
        	UI.getCurrent().navigate(View2.class, 123);	
        });
        add(navigate);
    }
}`

`

@Route(value = "Route2", layout = MainAppLayout.class)
public class View2 extends VerticalLayout implements HasUrlParameter<Integer> {

    public View2() {
    }
 
 @Override
	public void setParameter(BeforeEvent event, Integer parameter) {
		add(new Label(parameter.toString()));
	}
}
`

`
@Push
@Viewport("width=device-width, minimum-scale=1.0, initial-scale=1.0, user-scalable=yes")
public class MainAppLayout extends AppLayoutRouterLayout<LeftLayouts.Left> {

	public MainAppLayout() {
 
        init(AppLayoutBuilder.get(LeftLayouts.Left.class)
                .withTitle("App Layout")
                .withAppBar(AppBarBuilder.get()
                         .build())
                .withAppMenu(LeftAppMenuBuilder.get()
                        .addToSection(HEADER,
                                new LeftHeaderItem("Menu-Header", "Version 4.0.0", "images/logo.png"),
                                new LeftClickableItem("Clickable Entry", VaadinIcon.COG.create(), event -> Notification.show("onClick ..."))
                        )
                        .add(new LeftNavigationItem("Home", VaadinIcon.HOME.create(), View1.class))
                        .addToSection(FOOTER,
                                new LeftClickableItem("Clickable Entry", VaadinIcon.COG.create(), clickEvent -> Notification.show("onClick ..."))
                        )
                        .build())
                .withUpNavigation()
                .build());
        openDrawer();
    }
 
}

`
Step 1: click on navigate button
Step 2: click on back button.



![image](https://user-images.githubusercontent.com/30470304/76699024-00c97200-66e4-11ea-8570-6c56181d88a4.png)

**Comment by Winkefinger** [comment]
Hi!
I am having the same problem at the moment. I just ran into it while switching to this fantastic Addon.

As far as I can see, the following would help to fix it:
* In the constructor of LeftNavigationItem the route gets registered: `com.github.appreciated.app.layout.component.menu.left.items.LeftNavigationItem.LeftNavigationItem(String, Component, Class<? extends Component>)`
* There, `UpNavigationHelper.registerNavigationRoute(className);` is invoked. That fetches the route from RouteConfiguration via getUrl(className).

When a view uses `HasUrlParameter`, the registration via `RouteConfiguration.forSessionScope().getUrl(className);` fails.

With `RouteConfiguration.forSessionScope().getUrl(className, T);` (with T as view parameter), it should work.
There is also a method in `RouteConfiguration.getUrl` to pass a simple list of parameters, so maybe multiple constructors could be added to the `LeftNavigationItem`.


So,
* with another constructor in `LeftNavigationItem` to pass the T parameter
* and registering the route with the parameter in ``UpNavigationHelper.registerNavigationRoute``

it should work. Would at least be enough for my use case. It might be needed to add some things to the builders, but I do not use the fluent API in this case anyway.

Currently, I haven't checked out this project. The fix seems quite fast and easy though - if you need any help regarding this, please let me know :-)

**Comment by Winkefinger** [comment]
Hi!
I looked into this again and have a possible workaround. With the introduction of a new class (`ParameterizedLeftNavigationItem`) I am able to use HasUrlParameter-Views...
I also extended the Spring-Examples to feature 2 parameterized views.

I would like to push my branch, so we could use that as basis for further discussion. But I think I have no permission to do so.

So, just notify me if you want that contribution... ;-)

**Comment by appreciated** [comment]
Another possiblity would be to add support for classes with the `@HasUrlParameter` annotation directly to the `LeftNavigationItem`. I am currently very busy, so I don't really got the time to develop and test a solution for this. I will try to come up with a workaround tonight.

**Comment by weiliang2** [comment]
I’m not sure if this helps. It works in version 2.0.8. But not one version 4.
