### ISSUE TITLE
Vaadin 15 & Spring Boot 2.2.x: Unable to find template content

### ISSUE THREAD

**Issue by ajgassner** [appreciated/vaadin-app-layout#325]
4.0.0.rc4 is working fine with Vaadin 14 and npm mode with Spring Boot 2.1.8-RELEASE.
After upgrade to Spring Boot 2.2.5-RELEASE, Vaadin 15.0.2 and 4.0.0.rc5 the template content cannot be loaded. I'm using Maven.

There is already a closed and related bug with an insufficient fix description: https://github.com/appreciated/vaadin-app-layout/issues/303

@kunal-bhatia can you please describe what you did to fix the issue?

Stack trace:
```
Caused by: java.lang.IllegalStateException: Couldn't find the definition of the element with tag 'app-layout-left-responsive-hybrid' in any template file declared using '@JsModule' annotations. Check the availability of the template files in your WAR file or provide alternative implementation of the method getTemplateContent() which should return an element representing the content of the template file
	at com.vaadin.flow.component.polymertemplate.NpmTemplateParser.getTemplateContent(NpmTemplateParser.java:140)
	at com.vaadin.flow.component.polymertemplate.TemplateDataAnalyzer.parseTemplate(TemplateDataAnalyzer.java:200)
	at com.vaadin.flow.component.polymertemplate.TemplateInitializer.<init>(TemplateInitializer.java:91)
	at com.vaadin.flow.component.polymertemplate.PolymerTemplate.<init>(PolymerTemplate.java:88)
	at com.vaadin.flow.component.polymertemplate.PolymerTemplate.<init>(PolymerTemplate.java:103)
	at com.github.appreciated.app.layout.component.applayout.AppLayout.<init>(AppLayout.java:16)
	at com.github.appreciated.app.layout.component.applayout.AbstractLeftAppLayoutBase.<init>(AbstractLeftAppLayoutBase.java:41)
	at com.github.appreciated.app.layout.component.applayout.LeftLayouts$AbstractLeftResponsiveHybrid.<init>(LeftLayouts.java:98)
	at com.github.appreciated.app.layout.component.applayout.LeftLayouts$LeftResponsiveHybrid.<init>(LeftLayouts.java:123)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:166)
	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:404)
	at java.base/java.lang.Class.newInstance(Class.java:590)
	at com.github.appreciated.app.layout.component.builder.AppLayoutBuilder.get(AppLayoutBuilder.java:27)
	at at.wrwks.pba.search.ui.MainLayout.<init>(MainLayout.kt:49)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Constructor.call(CallerImpl.kt:41)
	at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:106)
	at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflection(KCallableImpl.kt:152)
	at kotlin.reflect.jvm.internal.KCallableImpl.callBy(KCallableImpl.kt:110)
	at org.springframework.beans.BeanUtils$KotlinDelegate.instantiateClass(BeanUtils.java:792)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:188)
	... 128 more
```

**Comment by appreciated** [comment]
[Flow has issues with addon resources at the moment](https://github.com/vaadin/flow/issues/7752)

**Comment by appreciated** [comment]
Vaadin 15.0.3 should have fixed this issue
