### ISSUE TITLE
Couldn't find the definition of the element with tag 'app-layout-left-responsive' in any template file declared using '@JsModule' annotations

### ISSUE THREAD

**Issue by lsiem** [appreciated/vaadin-app-layout#342]
I have a Spring Boot App with Vaadin and this addon. When I navigate to a view that "contains" the app menu (I built it like the examples), I get the following error message:
```Caused by: java.lang.IllegalStateException: Couldn't find the definition of the element with tag 'app-layout-left-responsive' in any template file declared using '@JsModule' annotations. Check the availability of the template files in your WAR file or provide alternative implementation of the method getTemplateContent() which should return an element representing the content of the template file
	at com.vaadin.flow.component.polymertemplate.NpmTemplateParser.getTemplateContent(NpmTemplateParser.java:143)
	at com.vaadin.flow.component.polymertemplate.TemplateDataAnalyzer.parseTemplate(TemplateDataAnalyzer.java:200)
	at com.vaadin.flow.component.polymertemplate.TemplateInitializer.<init>(TemplateInitializer.java:91)
	at com.vaadin.flow.component.polymertemplate.PolymerTemplate.<init>(PolymerTemplate.java:88)
	at com.vaadin.flow.component.polymertemplate.PolymerTemplate.<init>(PolymerTemplate.java:103)
	at com.github.appreciated.app.layout.component.applayout.AppLayout.<init>(AppLayout.java:16)
	at com.github.appreciated.app.layout.component.applayout.AbstractLeftAppLayoutBase.<init>(AbstractLeftAppLayoutBase.java:41)
	at com.github.appreciated.app.layout.component.applayout.LeftLayouts$AbstractLeftResponsive.<init>(LeftLayouts.java:62)
	at com.github.appreciated.app.layout.component.applayout.LeftLayouts$LeftResponsive.<init>(LeftLayouts.java:77)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.lang.Class.newInstance(Class.java:584)
	at com.github.appreciated.app.layout.component.builder.AppLayoutBuilder.get(AppLayoutBuilder.java:27)
	at de.hc.batteriefinder.layouts.MainAppLayout.<init>(MainAppLayout.java:50)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:204)
	... 135 more```

**To Reproduce**
Steps to reproduce the behavior:
1. Make a spring boot project with vaadin 14 and add the app layout
2. Create an abstract view
3. Create a basic view class which extends the abstract view
4. See error

**Expected behavior**
I want the view to show up instead of the error message :)

**Screenshots**
-----

** Additional Information:**
 - OS: Project created on Manjaro Linux and continued on Windows 10
 - Browser: MSEdge (Chromium)
 - Version: Spring (2.3.1.RELEASE), Vaadin (14.2.3), App-Layout (4.0.0.rc5)

**Comment by appreciated** [comment]
Hello @lsiem! First of all, Vaadin 14.2 is currently not yet really supported, due to a [non-released fix for styling issues](https://github.com/appreciated/vaadin-app-layout/issues/332). I currently don't have the time to test the next release. 
But I think your problem lies somewhere else. 
Before start digging please follow the instructions in [this answer](https://github.com/vaadin/flow/issues/6036#issuecomment-536986765) of a more or less related issue.
