### ISSUE TITLE
Vaadin 23: ERROR: Could not resolve "@vaadin/vaadin-element-mixin"

### ISSUE THREAD

**Issue by initialflame** [appreciated/vaadin-app-layout#467]
Hello,

i get this error with vaadin 23.2.6 on frontend-build:

2022-10-25 18:22:29.452  INFO 40244 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : Error: Build failed with 14 errors:
2022-10-25 18:22:29.452  INFO 40244 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : node_modules/@vaadin/flow-frontend/com/github/appreciated/app-layout/left/left-hybrid.js:12:27: ERROR: Could not resolve "@vaadin/vaadin-element-mixin"
2022-10-25 18:22:29.452  INFO 40244 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : node_modules/@vaadin/flow-frontend/com/github/appreciated/app-layout/left/left-overlay.js:12:27: ERROR: Could not resolve "@vaadin/vaadin-element-mixin"
2022-10-25 18:22:29.452  INFO 40244 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : node_modules/@vaadin/flow-frontend/com/github/appreciated/app-layout/left/left-responsive-double.js:12:27: ERROR: Could not resolve "@vaadin/vaadin-element-mixin"
2022-10-25 18:22:29.452  INFO 40244 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : node_modules/@vaadin/flow-frontend/com/github/appreciated/app-layout/left/left-responsive-hybrid-no-app-bar.js:12:27: ERROR: Could not resolve "@vaadin/vaadin-element-mixin"
2022-10-25 18:22:29.453  INFO 40244 --- [v-server-output] c.v.b.devserver.DevServerOutputTracker   : node_modules/@vaadin/flow-frontend/com/github/appreciated/app-layout/left/left-responsive-hybrid-overlay-no-app-bar.js:12:27: ERROR: Could not resolve "@vaadin/vaadin-element-mixin"

What i'am doing wrong or is it a bug ?

**Comment by aetasoul** [comment]
Same problem with version 23.3.5

```
[ERROR] [36mvite v3.2.5 building for production...
[ERROR] transforming...
[ERROR] ✓ 52 modules transformed.
[ERROR] [vite]: Rollup failed to resolve import "@vaadin/vaadin-element-mixin" from "frontend/generated/jar-resources/com/github/appreciated/app-layout/left/left-hybrid.js".
[ERROR] This is most likely unintended because it can break your application at runtime.
[ERROR] If you do want to externalize this module explicitly add it to
[ERROR] `build.rollupOptions.external`
[ERROR] error during build:
[ERROR] Error: [vite]: Rollup failed to resolve import "@vaadin/vaadin-element-mixin" from "frontend/generated/jar-resources/com/github/appreciated/app-layout/left/left-hybrid.js".
[ERROR] This is most likely unintended because it can break your application at runtime.
[ERROR] If you do want to externalize this module explicitly add it to
[ERROR] `build.rollupOptions.external`
[ERROR]     at onRollupWarning (file:///C:/Users/carlozanocco/Desktop/Progetti/energy/node_modules/.pnpm/vite@3.2.5/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:45832:19)
[ERROR]     at onwarn (file:///C:/Users/carlozanocco/Desktop/Progetti/energy/node_modules/.pnpm/vite@3.2.5/node_modules/vite/dist/node/chunks/dep-5605cfa4.js:45603:13)
[ERROR]     at Object.onwarn (file:///C:/Users/carlozanocco/Desktop/Progetti/energy/node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/es/shared/rollup.js:23263:13)
[ERROR]     at ModuleLoader.handleResolveId (file:///C:/Users/carlozanocco/Desktop/Progetti/energy/node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/es/shared/rollup.js:22158:26)
[ERROR]     at file:///C:/Users/carlozanocco/Desktop/Progetti/energy/node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/es/shared/rollup.js:22119:26
```

**Comment by jonmartinsolaas** [comment]
I just add the module with npm manually, as a workaround.

**Comment by rucko24** [comment]
> 23.3.5

Hi, how to solve it ? show me please.
